<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Список студентов</title>
        <link rel="stylesheet" href="css/students.css">
    </head>
    <body>
        <div class="pageName">
            Список абитуриентов
        </div>
        <div class="searchBlock">
            Поиск: [___________][Найти]
        </div>
        <div class="studentsTable">
            test index template <?php echo time(); ?><br/>
            <?php echo $text; ?>
        </div>
    </body>
</html>
